CREATE TABLE EST_USUARIO(
USU_ID NUMBER PRIMARY KEY,
USU_NOME VARCHAR2(200) NOT NULL,
USU_LOGIN VARCHAR2(200) NOT NULL,
USU_SENHA VARCHAR2(200) NOT NULL,
USU_EMAIL VARCHAR2(200) NOT NULL,
USU_STATUS  VARCHAR2(200) NOT NULL,
USU_DATA_CADASTRO DATE ,
USU_DATA_ULT_ACESSO DATE
)