CREATE TABLE EST_TELEFONE(
        TELEFONE_ID NUMBER PRIMARY KEY,
        TELEFONE_ID_USU NUMBER,
        TELEFONE_TIPO VARCHAR2(20),
        TELEFONE_NUMBER VARCHAR2(20),
        FOREIGN KEY (TELEFONE_ID_USU) REFERENCES EST_USUARIO(USU_ID)
)